# Generated by Django 4.2.2 on 2023-07-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.IntegerField(verbose_name='IdUsuario')),
                ('idLibro', models.IntegerField(verbose_name='IdLibro')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.IntegerField(verbose_name='IdUsuario')),
                ('idLibro', models.IntegerField(verbose_name='IdLibro')),
                ('paginaActual', models.IntegerField(verbose_name='PaginaActual')),
                ('fechaInicio', models.CharField(max_length=100, null=True, verbose_name='FechaInicio')),
                ('fechaFin', models.CharField(max_length=100, null=True, verbose_name='FechaFin')),
                ('estado', models.CharField(max_length=100, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=100, null=True, verbose_name='Autor')),
                ('editorial', models.CharField(max_length=100, null=True, verbose_name='Editorial')),
                ('isbn', models.CharField(max_length=100, null=True, verbose_name='isbn')),
                ('paginas', models.IntegerField(null=True, verbose_name='Paginas')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.IntegerField(verbose_name='IdUsuario')),
                ('idLibro', models.IntegerField(verbose_name='IdLibro')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuacion')),
                ('comentario', models.CharField(max_length=100, null=True, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
